# Generated by Django 6.1 on 2026-08-30 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('child', 'Child'), ('other', 'Other dependent')], default='self', max_length=10)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
